package com.kei.review.config;

import com.kei.review.questions.Question;
import com.kei.review.questions.QuestionDifficulty;
import com.kei.review.questions.QuestionRepository;
import com.kei.review.questions.QuestionSource;
import com.kei.review.topics.Topic;
import com.kei.review.topics.TopicRepository;
import com.kei.review.users.User;
import com.kei.review.users.UserRepository;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

@Component
@Order(1)
public class QuestionSeeder implements CommandLineRunner {
    private final QuestionRepository questionRepository;
    private final TopicRepository topicRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    public QuestionSeeder(
        QuestionRepository questionRepository,
        TopicRepository topicRepository,
        UserRepository userRepository,
        PasswordEncoder passwordEncoder
    ) {
        this.questionRepository = questionRepository;
        this.topicRepository = topicRepository;
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(String... args) {
        User owner = userRepository.findByEmail(SeedData.SYSTEM_USER_EMAIL)
            .orElseGet(() -> userRepository.save(User.builder()
                .email(SeedData.SYSTEM_USER_EMAIL)
                .passwordHash(passwordEncoder.encode(UUID.randomUUID().toString()))
                .fullName("BLEPP Seed Question Bank")
                .createdAt(Instant.now())
                .updatedAt(Instant.now())
                .build()));

        Map<String, Topic> topicsBySlug = topicRepository.findAll().stream()
            .collect(Collectors.toMap(Topic::getSlug, Function.identity(), (a, b) -> a));

        seedQuestions(owner, topicsBySlug);
    }

    private void seedQuestions(User owner, Map<String, Topic> topicsBySlug) {
        questions().stream()
            .filter(seed -> topicsBySlug.containsKey(seed.topicSlug()))
            .filter(seed -> !questionRepository.existsByOwnerEmailAndText(SeedData.SYSTEM_USER_EMAIL, seed.text()))
            .map(seed -> toQuestion(owner, topicsBySlug.get(seed.topicSlug()), seed))
            .forEach(questionRepository::save);
    }

    private Question toQuestion(User owner, Topic topic, SeedQuestion seed) {
        return Question.builder()
            .owner(owner)
            .topic(topic)
            .text(seed.text())
            .choices(seed.choices())
            .correctAnswerIndex(seed.correctAnswerIndex())
            .explanation(seed.explanation())
            .difficulty(seed.difficulty())
            .source(QuestionSource.MANUAL)
            .category(seed.category())
            .tags(seed.tags())
            .createdAt(Instant.now())
            .build();
    }

    private List<SeedQuestion> questions() {
        return List.of(
            q("general-psychology", "Which perspective explains behavior by emphasizing unconscious conflicts and early childhood experiences?", List.of("Behavioral", "Psychodynamic", "Humanistic", "Cognitive"), 1, QuestionDifficulty.EASY, "Psychodynamic theory focuses on unconscious motives and early experiences as drivers of behavior.", "Theories", List.of("general-psychology", "theories")),
            q("general-psychology", "A researcher gives one group caffeine and another group a placebo before a memory test. What is caffeine in this design?", List.of("Dependent variable", "Independent variable", "Confounding variable", "Random variable"), 1, QuestionDifficulty.EASY, "The independent variable is manipulated by the researcher.", "Research Methods", List.of("research", "experimental-design")),
            q("general-psychology", "Which schedule of reinforcement produces high, steady responding and is common in gambling behavior?", List.of("Fixed ratio", "Fixed interval", "Variable ratio", "Variable interval"), 2, QuestionDifficulty.MEDIUM, "Variable ratio schedules reinforce after unpredictable numbers of responses, producing persistent responding.", "Learning", List.of("learning", "reinforcement")),
            q("general-psychology", "According to Piaget, conservation is typically mastered during which stage?", List.of("Sensorimotor", "Preoperational", "Concrete operational", "Formal operational"), 2, QuestionDifficulty.EASY, "Children in the concrete operational stage can understand conservation and reversibility.", "Development", List.of("piaget", "development")),
            q("general-psychology", "Which memory system briefly stores auditory information for a few seconds?", List.of("Iconic memory", "Echoic memory", "Procedural memory", "Semantic memory"), 1, QuestionDifficulty.EASY, "Echoic memory is the sensory register for sound.", "Cognition", List.of("memory", "cognition")),
            q("general-psychology", "A test that gives similar scores across repeated administrations is best described as having high what?", List.of("Validity", "Reliability", "Sensitivity", "Utility"), 1, QuestionDifficulty.EASY, "Reliability refers to consistency of measurement.", "Assessment Basics", List.of("measurement", "reliability")),
            q("general-psychology", "In Maslow's hierarchy, which need is addressed before esteem needs?", List.of("Self-actualization", "Belongingness and love", "Transcendence", "Aesthetic needs"), 1, QuestionDifficulty.EASY, "Belongingness and love needs precede esteem needs in Maslow's classic hierarchy.", "Motivation", List.of("motivation", "maslow")),
            q("general-psychology", "The tendency to attribute another person's behavior to disposition while underestimating situational factors is called what?", List.of("Self-serving bias", "Confirmation bias", "Fundamental attribution error", "Actor-observer advantage"), 2, QuestionDifficulty.MEDIUM, "The fundamental attribution error overemphasizes internal causes for others' behavior.", "Social Psychology", List.of("social-psychology", "attribution")),
            q("general-psychology", "Which structure is most directly associated with forming new explicit memories?", List.of("Amygdala", "Hippocampus", "Cerebellum", "Medulla"), 1, QuestionDifficulty.EASY, "The hippocampus is central to consolidation of new explicit memories.", "Biopsychology", List.of("brain", "memory")),
            q("general-psychology", "A client solves a problem by suddenly seeing a new relationship among its parts. This is an example of what?", List.of("Insight", "Shaping", "Priming", "Habituation"), 0, QuestionDifficulty.MEDIUM, "Insight is a sudden restructuring or realization that leads to problem solution.", "Cognition", List.of("problem-solving", "insight")),
            q("general-psychology", "Which school of psychology emphasized observable behavior rather than mental processes?", List.of("Structuralism", "Behaviorism", "Gestalt psychology", "Psychoanalysis"), 1, QuestionDifficulty.EASY, "Behaviorism focused on observable behavior and learning through environmental contingencies.", "History", List.of("behaviorism", "history")),
            q("general-psychology", "In classical conditioning, what is the neutral stimulus after it has been paired with an unconditioned stimulus?", List.of("Conditioned stimulus", "Unconditioned response", "Discriminative stimulus", "Reinforcer"), 0, QuestionDifficulty.EASY, "After pairing, the neutral stimulus becomes a conditioned stimulus capable of eliciting a conditioned response.", "Learning", List.of("classical-conditioning", "learning")),
            q("general-psychology", "Which concept refers to the ability to understand that others have beliefs and perspectives different from one's own?", List.of("Object permanence", "Theory of mind", "Egocentrism", "Conservation"), 1, QuestionDifficulty.MEDIUM, "Theory of mind is the ability to infer and understand other people's mental states.", "Development", List.of("theory-of-mind", "development")),
            q("general-psychology", "Which neurotransmitter is most commonly associated with reward pathways and reinforcement learning?", List.of("Dopamine", "GABA", "Acetylcholine", "Serotonin"), 0, QuestionDifficulty.MEDIUM, "Dopamine is strongly linked to reward processing and reinforcement learning.", "Biopsychology", List.of("dopamine", "reward")),
            q("general-psychology", "A correlation coefficient close to -1.00 indicates what?", List.of("No relationship", "A strong negative relationship", "A weak positive relationship", "Proof of causation"), 1, QuestionDifficulty.EASY, "A coefficient near -1.00 indicates a strong inverse association between variables.", "Research Methods", List.of("correlation", "statistics")),
            q("general-psychology", "Which Gestalt principle states that people perceive objects near each other as belonging together?", List.of("Closure", "Similarity", "Proximity", "Continuity"), 2, QuestionDifficulty.EASY, "The principle of proximity says nearby elements are perceived as grouped.", "Perception", List.of("gestalt", "perception")),
            q("general-psychology", "What is the main purpose of random assignment in an experiment?", List.of("To select a representative sample", "To reduce preexisting group differences", "To guarantee external validity", "To increase demand characteristics"), 1, QuestionDifficulty.MEDIUM, "Random assignment helps distribute participant characteristics evenly across conditions.", "Research Methods", List.of("random-assignment", "experimental-design")),
            q("general-psychology", "Which term describes memory for skills and procedures such as riding a bicycle?", List.of("Semantic memory", "Episodic memory", "Procedural memory", "Echoic memory"), 2, QuestionDifficulty.EASY, "Procedural memory stores learned skills and action routines.", "Cognition", List.of("memory", "procedural")),
            q("general-psychology", "Which branch of psychology studies how people influence and relate to one another?", List.of("Social psychology", "Comparative psychology", "Neuropsychology", "Psychometrics"), 0, QuestionDifficulty.EASY, "Social psychology examines social influence, relationships, attitudes, and group behavior.", "Social Psychology", List.of("social-psychology", "overview")),
            q("general-psychology", "What does operational definition mean in research?", List.of("A legal definition of a variable", "A precise description of how a variable is measured or manipulated", "A broad theoretical assumption", "A participant's subjective interpretation"), 1, QuestionDifficulty.MEDIUM, "Operational definitions specify exactly how constructs are measured or manipulated in a study.", "Research Methods", List.of("operational-definition", "measurement")),

            q("abnormal-psychology", "Which symptom is most characteristic of a panic attack?", List.of("Persistent low mood for two weeks", "Sudden intense fear with physical arousal", "Recurrent intrusive trauma memories only", "Gradual loss of cognitive ability"), 1, QuestionDifficulty.EASY, "Panic attacks involve abrupt surges of fear with symptoms such as palpitations or shortness of breath.", "Anxiety Disorders", List.of("panic", "anxiety")),
            q("abnormal-psychology", "A person reports hearing voices commenting on their actions when no one is present. This is best classified as what?", List.of("Delusion", "Compulsion", "Hallucination", "Dissociation"), 2, QuestionDifficulty.EASY, "A hallucination is a sensory perception without an external stimulus.", "Psychotic Disorders", List.of("psychosis", "hallucination")),
            q("abnormal-psychology", "Which feature distinguishes obsessions from compulsions?", List.of("Obsessions are intrusive thoughts; compulsions are repetitive behaviors or mental acts", "Obsessions are voluntary; compulsions are always pleasurable", "Obsessions require psychosis; compulsions require mania", "Obsessions occur only in children; compulsions occur only in adults"), 0, QuestionDifficulty.MEDIUM, "Obsessions are intrusive thoughts or urges, while compulsions are acts performed to reduce distress.", "Obsessive-Compulsive Disorders", List.of("ocd", "diagnosis")),
            q("abnormal-psychology", "A manic episode requires abnormally elevated or irritable mood plus increased energy lasting at least how long, unless hospitalization occurs?", List.of("One day", "Four days", "One week", "One month"), 2, QuestionDifficulty.MEDIUM, "A manic episode typically lasts at least one week or requires hospitalization.", "Mood Disorders", List.of("bipolar", "mania")),
            q("abnormal-psychology", "Which treatment is most strongly associated with challenging automatic negative thoughts?", List.of("Client-centered therapy", "Cognitive-behavioral therapy", "Classical psychoanalysis", "Aversion therapy only"), 1, QuestionDifficulty.EASY, "CBT targets maladaptive thoughts and behaviors through structured techniques.", "Treatment", List.of("cbt", "therapy")),
            q("abnormal-psychology", "Marked fear of being judged in social situations most directly suggests which disorder?", List.of("Specific phobia", "Social anxiety disorder", "Separation anxiety disorder", "Illness anxiety disorder"), 1, QuestionDifficulty.EASY, "Social anxiety disorder centers on fear of negative evaluation in social or performance situations.", "Anxiety Disorders", List.of("social-anxiety", "diagnosis")),
            q("abnormal-psychology", "Which is a negative symptom of schizophrenia?", List.of("Auditory hallucinations", "Persecutory delusions", "Avolition", "Loose associations"), 2, QuestionDifficulty.MEDIUM, "Avolition is a reduction in motivation and goal-directed activity.", "Psychotic Disorders", List.of("schizophrenia", "negative-symptoms")),
            q("abnormal-psychology", "Persistent fear of gaining weight with significantly low body weight is most consistent with what?", List.of("Bulimia nervosa", "Anorexia nervosa", "Binge-eating disorder", "Body dysmorphic disorder"), 1, QuestionDifficulty.EASY, "Anorexia nervosa includes restriction leading to low body weight and intense fear of weight gain.", "Eating Disorders", List.of("eating-disorders", "diagnosis")),
            q("abnormal-psychology", "Exposure and response prevention is a first-line behavioral treatment for which condition?", List.of("Obsessive-compulsive disorder", "Dissociative identity disorder", "Narcissistic personality disorder", "Major neurocognitive disorder"), 0, QuestionDifficulty.MEDIUM, "ERP exposes clients to triggers while preventing compulsive rituals.", "Treatment", List.of("ocd", "erp")),
            q("abnormal-psychology", "A diagnosis of PTSD requires exposure to trauma plus symptoms from intrusion, avoidance, negative mood/cognition, and what other cluster?", List.of("Grandiosity", "Hyperarousal", "Language impairment", "Body image disturbance"), 1, QuestionDifficulty.HARD, "PTSD includes intrusion, avoidance, negative alterations, and hyperarousal symptoms.", "Trauma Disorders", List.of("ptsd", "diagnosis")),
            q("abnormal-psychology", "Which disorder involves excessive worry occurring more days than not for at least six months?", List.of("Panic disorder", "Generalized anxiety disorder", "Specific phobia", "Acute stress disorder"), 1, QuestionDifficulty.EASY, "Generalized anxiety disorder involves persistent, excessive worry across domains for at least six months.", "Anxiety Disorders", List.of("gad", "anxiety")),
            q("abnormal-psychology", "Which term describes a fixed false belief maintained despite contrary evidence?", List.of("Hallucination", "Delusion", "Compulsion", "Flashback"), 1, QuestionDifficulty.EASY, "A delusion is a fixed false belief not supported by evidence or cultural context.", "Psychotic Disorders", List.of("delusion", "psychosis")),
            q("abnormal-psychology", "Which personality disorder is characterized by instability in relationships, self-image, affect, and impulsivity?", List.of("Avoidant personality disorder", "Borderline personality disorder", "Schizoid personality disorder", "Obsessive-compulsive personality disorder"), 1, QuestionDifficulty.MEDIUM, "Borderline personality disorder includes affective instability, identity disturbance, relationship instability, and impulsivity.", "Personality Disorders", List.of("borderline", "personality-disorders")),
            q("abnormal-psychology", "Which condition involves recurrent episodes of eating large amounts of food with a sense of loss of control and compensatory behavior?", List.of("Anorexia nervosa", "Bulimia nervosa", "Pica", "Avoidant/restrictive food intake disorder"), 1, QuestionDifficulty.MEDIUM, "Bulimia nervosa includes binge eating episodes and compensatory behaviors such as purging or excessive exercise.", "Eating Disorders", List.of("bulimia", "diagnosis")),
            q("abnormal-psychology", "Which therapy is especially associated with validation, mindfulness, and emotion regulation skills for borderline personality disorder?", List.of("Dialectical behavior therapy", "Systematic desensitization", "Token economy", "Electroconvulsive therapy"), 0, QuestionDifficulty.MEDIUM, "DBT teaches emotion regulation, distress tolerance, mindfulness, and interpersonal effectiveness skills.", "Treatment", List.of("dbt", "borderline")),
            q("abnormal-psychology", "Which symptom cluster in major depressive disorder includes loss of interest or pleasure?", List.of("Anhedonia", "Flight of ideas", "Grandiosity", "Catatonia"), 0, QuestionDifficulty.EASY, "Anhedonia is diminished interest or pleasure and is a core depressive symptom.", "Mood Disorders", List.of("depression", "anhedonia")),
            q("abnormal-psychology", "A sudden inability to recall important autobiographical information after stress is most consistent with what?", List.of("Dissociative amnesia", "Conversion disorder", "Illness anxiety disorder", "Cyclothymic disorder"), 0, QuestionDifficulty.MEDIUM, "Dissociative amnesia involves inability to recall autobiographical information, often related to trauma or stress.", "Dissociative Disorders", List.of("dissociation", "amnesia")),
            q("abnormal-psychology", "Which disorder features persistent attention problems, hyperactivity, or impulsivity that interferes with functioning?", List.of("Autism spectrum disorder", "ADHD", "Specific learning disorder", "Conduct disorder"), 1, QuestionDifficulty.EASY, "ADHD involves developmentally inappropriate inattention and/or hyperactivity-impulsivity with functional impairment.", "Neurodevelopmental Disorders", List.of("adhd", "diagnosis")),
            q("abnormal-psychology", "Which concept describes the co-occurrence of two or more disorders in the same person?", List.of("Comorbidity", "Differential diagnosis", "Etiology", "Remission"), 0, QuestionDifficulty.EASY, "Comorbidity is the presence of multiple disorders in the same individual.", "Diagnosis", List.of("comorbidity", "diagnosis")),
            q("abnormal-psychology", "Which prevention level targets people who already show early symptoms to reduce disorder severity?", List.of("Primary prevention", "Secondary prevention", "Tertiary prevention", "Universal prevention only"), 1, QuestionDifficulty.MEDIUM, "Secondary prevention focuses on early detection and intervention to limit progression.", "Prevention", List.of("prevention", "intervention")),

            q("psychological-assessment", "Which property indicates that a test measures what it claims to measure?", List.of("Reliability", "Validity", "Norming", "Objectivity"), 1, QuestionDifficulty.EASY, "Validity concerns whether evidence supports the intended interpretation of test scores.", "Psychometrics", List.of("validity", "assessment")),
            q("psychological-assessment", "A percentile rank of 75 means the examinee scored how?", List.of("75 percent correct", "Higher than about 75 percent of the norm group", "75 standard deviations above the mean", "At the 75th item difficulty level"), 1, QuestionDifficulty.EASY, "Percentile rank compares an examinee to the norm group.", "Scores and Norms", List.of("norms", "percentile")),
            q("psychological-assessment", "Cronbach's alpha is most commonly used to estimate what?", List.of("Inter-rater agreement", "Internal consistency", "Predictive validity", "Factor rotation"), 1, QuestionDifficulty.MEDIUM, "Cronbach's alpha estimates how consistently items measure a construct.", "Reliability", List.of("cronbach-alpha", "reliability")),
            q("psychological-assessment", "Which score has a mean of 100 and standard deviation of 15 in many intelligence tests?", List.of("T score", "z score", "Deviation IQ", "Stanine"), 2, QuestionDifficulty.EASY, "Deviation IQ scores commonly use mean 100 and SD 15.", "Intelligence Testing", List.of("iq", "standard-scores")),
            q("psychological-assessment", "A test developer correlates entrance exam scores with first-year grades. This primarily examines what?", List.of("Face validity", "Predictive criterion validity", "Internal consistency", "Alternate-form reliability"), 1, QuestionDifficulty.MEDIUM, "Predictive validity evaluates how well scores forecast future criterion performance.", "Validity", List.of("criterion-validity", "prediction")),
            q("psychological-assessment", "Which assessment method uses ambiguous stimuli to elicit responses interpreted as reflecting personality dynamics?", List.of("Projective technique", "Structured interview", "Behavioral checklist", "Achievement test"), 0, QuestionDifficulty.EASY, "Projective techniques use ambiguous stimuli such as inkblots or pictures.", "Personality Assessment", List.of("projective", "personality")),
            q("psychological-assessment", "If two clinicians independently score the same protocol similarly, the scoring shows high what?", List.of("Split-half reliability", "Inter-rater reliability", "Content validity", "Concurrent validity"), 1, QuestionDifficulty.EASY, "Inter-rater reliability is consistency between different raters.", "Reliability", List.of("inter-rater", "scoring")),
            q("psychological-assessment", "Which practice best supports ethical test interpretation?", List.of("Interpreting scores without context", "Using only one test for all decisions", "Integrating test data with history and observations", "Sharing raw test materials publicly"), 2, QuestionDifficulty.MEDIUM, "Ethical interpretation integrates multiple sources and protects test security.", "Assessment Ethics", List.of("ethics", "interpretation")),
            q("psychological-assessment", "A standard error of measurement helps estimate what?", List.of("The number of items on a test", "Likely range around an observed score", "The test's copyright status", "The examinee's percentile rank only"), 1, QuestionDifficulty.MEDIUM, "SEM estimates the uncertainty around an observed score.", "Measurement Error", List.of("sem", "psychometrics")),
            q("psychological-assessment", "Which type of validity evidence examines whether test items adequately represent the construct domain?", List.of("Content validity", "Predictive validity", "Face validity", "Incremental validity"), 0, QuestionDifficulty.MEDIUM, "Content validity concerns how well items sample the intended domain.", "Validity", List.of("content-validity", "test-development")),
            q("psychological-assessment", "Which score has a mean of 50 and standard deviation of 10?", List.of("z score", "T score", "Stanine", "Percentile rank"), 1, QuestionDifficulty.EASY, "T scores commonly have a mean of 50 and a standard deviation of 10.", "Scores and Norms", List.of("standard-scores", "t-score")),
            q("psychological-assessment", "Which reliability estimate compares scores from the same test administered at two different times?", List.of("Internal consistency", "Test-retest reliability", "Inter-rater reliability", "Content validity"), 1, QuestionDifficulty.EASY, "Test-retest reliability evaluates score stability across time.", "Reliability", List.of("test-retest", "reliability")),
            q("psychological-assessment", "What is a norm-referenced test primarily designed to do?", List.of("Compare an examinee to a reference group", "Measure only mastery of fixed objectives", "Eliminate all measurement error", "Diagnose without clinical judgment"), 0, QuestionDifficulty.EASY, "Norm-referenced interpretation compares performance against a defined norm group.", "Scores and Norms", List.of("norms", "interpretation")),
            q("psychological-assessment", "Which type of validity evidence is supported when test scores correlate with a similar established measure taken at the same time?", List.of("Concurrent validity", "Predictive validity", "Face validity", "Test-retest reliability"), 0, QuestionDifficulty.MEDIUM, "Concurrent validity evidence relates scores to a relevant criterion measured at about the same time.", "Validity", List.of("concurrent-validity", "criterion")),
            q("psychological-assessment", "Which assessment bias can occur when norms do not represent the population being tested?", List.of("Sampling bias", "Practice effect", "Halo effect", "Regression to the mean"), 0, QuestionDifficulty.MEDIUM, "Unrepresentative norms can bias interpretation for examinees outside the norm sample.", "Assessment Fairness", List.of("bias", "norms")),
            q("psychological-assessment", "Which interview format uses standardized questions and scoring rules?", List.of("Unstructured interview", "Structured interview", "Informal conversation", "Free association"), 1, QuestionDifficulty.EASY, "Structured interviews improve consistency by using predetermined questions and scoring.", "Clinical Assessment", List.of("interview", "structured")),
            q("psychological-assessment", "What is the main purpose of a test manual?", List.of("To replace informed consent", "To document administration, scoring, norms, reliability, and validity evidence", "To keep all scoring secret from qualified users", "To guarantee diagnostic accuracy"), 1, QuestionDifficulty.MEDIUM, "A test manual provides technical and procedural information needed for appropriate test use.", "Test Use", List.of("test-manual", "psychometrics")),
            q("psychological-assessment", "Which error occurs when an examiner gives extra help not allowed by standardized procedures?", List.of("Administration error", "Construct validity", "Base rate neglect", "Random sampling"), 0, QuestionDifficulty.EASY, "Departures from standardized administration can compromise score interpretation.", "Administration", List.of("standardization", "administration-error")),
            q("psychological-assessment", "Which scale type has equal intervals but no true zero point?", List.of("Nominal", "Ordinal", "Interval", "Ratio"), 2, QuestionDifficulty.MEDIUM, "Interval scales have equal units but lack a true zero point.", "Measurement", List.of("measurement-scales", "statistics")),
            q("psychological-assessment", "What does incremental validity ask?", List.of("Whether a test adds useful prediction beyond existing information", "Whether all items look valid to laypeople", "Whether scores are normally distributed", "Whether the test is easy to administer"), 0, QuestionDifficulty.HARD, "Incremental validity evaluates whether a measure improves prediction or decision-making beyond what is already available.", "Validity", List.of("incremental-validity", "prediction")),

            q("industrial-organizational-psychology", "A structured interview improves selection decisions mainly because it increases what?", List.of("Halo effect", "Reliability and job-related consistency", "Applicant anxiety", "Adverse impact automatically"), 1, QuestionDifficulty.MEDIUM, "Structured interviews use standardized questions and scoring, improving consistency and validity.", "Selection", List.of("selection", "interviews")),
            q("industrial-organizational-psychology", "Which term describes the degree to which a test predicts job performance?", List.of("Utility", "Criterion-related validity", "Job enrichment", "Organizational commitment"), 1, QuestionDifficulty.EASY, "Criterion-related validity links predictor scores to job performance criteria.", "Selection", List.of("criterion-validity", "job-performance")),
            q("industrial-organizational-psychology", "Herzberg's two-factor theory distinguishes motivators from what?", List.of("Schemas", "Hygiene factors", "Trait factors", "Group norms"), 1, QuestionDifficulty.EASY, "Hygiene factors reduce dissatisfaction, while motivators promote satisfaction.", "Motivation", List.of("herzberg", "motivation")),
            q("industrial-organizational-psychology", "A job analysis is primarily used to identify what?", List.of("Employee personality disorders", "Tasks, duties, responsibilities, and required KSAOs", "Stock market risk", "Union membership only"), 1, QuestionDifficulty.EASY, "Job analysis clarifies work tasks and required knowledge, skills, abilities, and other characteristics.", "Job Analysis", List.of("job-analysis", "ksaos")),
            q("industrial-organizational-psychology", "Which leadership style emphasizes inspiring followers through vision and individualized consideration?", List.of("Transactional", "Transformational", "Laissez-faire", "Autocratic"), 1, QuestionDifficulty.EASY, "Transformational leadership motivates through vision, inspiration, and individual consideration.", "Leadership", List.of("leadership", "transformational")),
            q("industrial-organizational-psychology", "Adverse impact in selection is commonly evaluated with which guideline?", List.of("Four-fifths rule", "Yerkes-Dodson law", "Law of effect", "Central limit theorem"), 0, QuestionDifficulty.MEDIUM, "The four-fifths rule is a common screening guideline for adverse impact.", "Legal and Ethical Issues", List.of("adverse-impact", "selection")),
            q("industrial-organizational-psychology", "Which intervention redesigns work to increase autonomy, task identity, and feedback?", List.of("Job enrichment", "Downsizing", "Piece-rate pay", "Paired comparison"), 0, QuestionDifficulty.MEDIUM, "Job enrichment increases motivating characteristics of work.", "Work Motivation", List.of("job-design", "enrichment")),
            q("industrial-organizational-psychology", "Organizational citizenship behavior refers to what?", List.of("Required job tasks only", "Voluntary behaviors that support organizational functioning", "Counterproductive work behavior", "Formal disciplinary action"), 1, QuestionDifficulty.EASY, "OCBs are discretionary behaviors that help the organization.", "Organizational Behavior", List.of("ocb", "work-behavior")),
            q("industrial-organizational-psychology", "Which rating error occurs when one positive trait influences ratings of unrelated traits?", List.of("Leniency", "Central tendency", "Halo effect", "Contrast effect"), 2, QuestionDifficulty.EASY, "The halo effect occurs when a general impression biases specific ratings.", "Performance Appraisal", List.of("rating-errors", "halo-effect")),
            q("industrial-organizational-psychology", "Burnout is classically associated with exhaustion, reduced personal accomplishment, and what?", List.of("Depersonalization or cynicism", "Euphoria", "Formal operations", "Sublimation"), 0, QuestionDifficulty.MEDIUM, "Burnout includes emotional exhaustion, depersonalization/cynicism, and reduced accomplishment.", "Occupational Health", List.of("burnout", "well-being")),
            q("industrial-organizational-psychology", "Which selection method samples tasks similar to those performed on the job?", List.of("Work sample test", "Projective test", "Interest inventory only", "Unstructured interview"), 0, QuestionDifficulty.EASY, "Work sample tests ask applicants to perform job-relevant tasks and can provide strong validity evidence.", "Selection", List.of("work-sample", "selection")),
            q("industrial-organizational-psychology", "Which term refers to the financial value of using a selection procedure?", List.of("Utility", "Reliability", "Job satisfaction", "Role ambiguity"), 0, QuestionDifficulty.MEDIUM, "Utility analysis estimates the practical or economic value of selection tools.", "Selection", List.of("utility", "selection")),
            q("industrial-organizational-psychology", "Which theory proposes that motivation depends on expectancy, instrumentality, and valence?", List.of("Equity theory", "Expectancy theory", "Goal-setting theory", "Two-factor theory"), 1, QuestionDifficulty.MEDIUM, "Expectancy theory links motivation to belief in effort-performance links, performance-outcome links, and outcome value.", "Motivation", List.of("expectancy-theory", "motivation")),
            q("industrial-organizational-psychology", "Which job characteristic refers to the degree of freedom and discretion employees have?", List.of("Task identity", "Autonomy", "Skill variety", "Feedback"), 1, QuestionDifficulty.EASY, "Autonomy is the degree of independence and discretion in scheduling and performing work.", "Job Design", List.of("autonomy", "job-characteristics")),
            q("industrial-organizational-psychology", "Which performance appraisal method compares employees directly against one another?", List.of("Paired comparison", "Behaviorally anchored rating scale", "Critical incident log", "Self-report inventory"), 0, QuestionDifficulty.MEDIUM, "Paired comparison ranks employees by comparing them in pairs.", "Performance Appraisal", List.of("appraisal", "paired-comparison")),
            q("industrial-organizational-psychology", "Role ambiguity occurs when employees lack clarity about what?", List.of("Their job expectations and responsibilities", "Their personality type", "The organization's legal registration", "The number of competitors"), 0, QuestionDifficulty.EASY, "Role ambiguity is uncertainty about duties, expectations, or standards for performance.", "Organizational Behavior", List.of("role-ambiguity", "work-stress")),
            q("industrial-organizational-psychology", "Which type of commitment reflects emotional attachment to an organization?", List.of("Continuance commitment", "Affective commitment", "Normative commitment", "Instrumental commitment"), 1, QuestionDifficulty.MEDIUM, "Affective commitment is emotional attachment and identification with the organization.", "Organizational Commitment", List.of("commitment", "affective")),
            q("industrial-organizational-psychology", "Which training evaluation level in Kirkpatrick's model measures learning?", List.of("Participant reactions", "Knowledge or skill acquisition", "Business results only", "Return on investment only"), 1, QuestionDifficulty.MEDIUM, "The learning level evaluates whether trainees acquired intended knowledge, skills, or attitudes.", "Training", List.of("kirkpatrick", "training")),
            q("industrial-organizational-psychology", "Which conflict management style is high in assertiveness and high in cooperativeness?", List.of("Avoiding", "Competing", "Collaborating", "Accommodating"), 2, QuestionDifficulty.MEDIUM, "Collaborating seeks solutions that satisfy both parties and is high in assertiveness and cooperativeness.", "Conflict", List.of("conflict-management", "collaboration")),
            q("industrial-organizational-psychology", "Which workplace behavior intentionally harms the organization or its members?", List.of("Organizational citizenship behavior", "Counterproductive work behavior", "Job crafting", "Prosocial motivation"), 1, QuestionDifficulty.EASY, "Counterproductive work behavior includes harmful actions such as theft, sabotage, or harassment.", "Work Behavior", List.of("cwb", "organizational-behavior")),

            q("ethics-ra-10029", "Under ethical practice, informed consent should generally include which element?", List.of("Only the psychologist's credentials", "Nature, purpose, risks, benefits, and limits of confidentiality", "A guarantee of improvement", "The raw answer key for tests"), 1, QuestionDifficulty.EASY, "Informed consent requires enough information for a client to make a voluntary decision.", "Consent", List.of("ethics", "informed-consent")),
            q("ethics-ra-10029", "Which action best protects test security?", List.of("Posting test items online", "Limiting access to qualified users and secure conditions", "Letting clients keep protocols", "Using tests without manuals"), 1, QuestionDifficulty.EASY, "Test security requires controlled access and proper handling of materials.", "Testing Ethics", List.of("test-security", "assessment")),
            q("ethics-ra-10029", "When a client poses imminent serious risk to self or others, confidentiality may be limited because of what duty?", List.of("Duty to warn or protect", "Duty to advertise", "Duty to publish", "Duty to diagnose"), 0, QuestionDifficulty.MEDIUM, "Confidentiality has exceptions when serious imminent harm may require protective action.", "Confidentiality", List.of("confidentiality", "risk")),
            q("ethics-ra-10029", "A psychologist should practice only within areas supported by training and experience. This reflects what principle?", List.of("Competence", "Transference", "Randomization", "Extinction"), 0, QuestionDifficulty.EASY, "Competence requires appropriate education, training, supervised experience, or consultation.", "Professional Competence", List.of("competence", "practice")),
            q("ethics-ra-10029", "Which is the best response to a potential multiple relationship?", List.of("Proceed because it is always harmless", "Evaluate risk of impaired objectivity or harm and avoid when inappropriate", "Hide it from the client", "Accept only if it is profitable"), 1, QuestionDifficulty.MEDIUM, "Multiple relationships require careful evaluation and avoidance when they risk harm or impaired judgment.", "Boundaries", List.of("multiple-relationships", "boundaries")),
            q("ethics-ra-10029", "RA 10029 is most directly associated with what in the Philippines?", List.of("Regulation of psychology and psychometrics practice", "Public school curriculum standards only", "Hospital construction permits", "Labor wage computation"), 0, QuestionDifficulty.EASY, "RA 10029 is the Philippine Psychology Act regulating psychology and psychometrics practice.", "RA 10029", List.of("ra-10029", "law")),
            q("ethics-ra-10029", "Which documentation practice is most ethical?", List.of("Keeping accurate, timely, and secure records", "Destroying all records immediately", "Recording only favorable findings", "Sharing records without authorization"), 0, QuestionDifficulty.EASY, "Ethical documentation is accurate, timely, secure, and consistent with law and policy.", "Records", List.of("records", "documentation")),
            q("ethics-ra-10029", "When using psychological tests, the practitioner should primarily select instruments based on what?", List.of("Popularity on social media", "Appropriateness for purpose, population, and evidence base", "Lowest price only", "Shortest administration time only"), 1, QuestionDifficulty.MEDIUM, "Tests should fit the assessment purpose, client characteristics, and psychometric evidence.", "Testing Ethics", List.of("test-selection", "validity")),
            q("ethics-ra-10029", "If a conflict arises between an organization's demand and ethical standards, the psychologist should first do what?", List.of("Automatically resign without discussion", "Clarify the conflict and seek ethically appropriate resolution", "Ignore ethical standards", "Follow only the highest-ranking person"), 1, QuestionDifficulty.HARD, "Ethical practice requires identifying conflicts and resolving them in a way consistent with professional obligations.", "Ethical Decision-Making", List.of("ethics", "conflict")),
            q("ethics-ra-10029", "Which statement best describes confidentiality in psychological services?", List.of("It is absolute in every situation", "It has limits that should be explained early in the professional relationship", "It applies only to minors", "It prevents all record keeping"), 1, QuestionDifficulty.EASY, "Clients should be informed about confidentiality and its legal or ethical limits.", "Confidentiality", List.of("confidentiality", "consent")),
            q("ethics-ra-10029", "Which action best reflects respect for client autonomy?", List.of("Withholding all information to avoid worry", "Supporting informed, voluntary decision-making", "Promising outcomes before treatment", "Ignoring client preferences"), 1, QuestionDifficulty.EASY, "Respect for autonomy includes informed choice and voluntary participation.", "Ethical Principles", List.of("autonomy", "ethics")),
            q("ethics-ra-10029", "What should a psychologist do when competence is insufficient for a requested service?", List.of("Proceed without disclosure", "Seek supervision, consultation, training, or refer when appropriate", "Use any available test", "Rely only on intuition"), 1, QuestionDifficulty.MEDIUM, "Ethical practice requires obtaining competence or arranging appropriate referral or consultation.", "Professional Competence", List.of("competence", "referral")),
            q("ethics-ra-10029", "Which practice supports privacy when transmitting client records electronically?", List.of("Using secure authorized channels", "Sending records to any requester", "Posting summaries publicly", "Removing all documentation standards"), 0, QuestionDifficulty.EASY, "Electronic records should be transmitted through secure and authorized methods.", "Records", List.of("privacy", "records")),
            q("ethics-ra-10029", "Which is an ethical concern in dual or multiple relationships?", List.of("Possible impaired objectivity or exploitation", "Reduced paperwork only", "Guaranteed better rapport", "Automatic legal approval"), 0, QuestionDifficulty.MEDIUM, "Multiple relationships can create risks of harm, exploitation, or impaired professional judgment.", "Boundaries", List.of("dual-relationships", "ethics")),
            q("ethics-ra-10029", "Which response best protects examinees when using assessment results?", List.of("Report scores without explanation", "Explain results in language appropriate to the recipient", "Release raw test items broadly", "Ignore limitations of the test"), 1, QuestionDifficulty.MEDIUM, "Assessment feedback should be understandable and include appropriate context and limitations.", "Assessment Ethics", List.of("feedback", "assessment")),
            q("ethics-ra-10029", "Which principle is most directly involved in avoiding harm to clients?", List.of("Nonmaleficence", "Randomization", "Extinction", "Criterion validity"), 0, QuestionDifficulty.EASY, "Nonmaleficence refers to the ethical obligation to avoid causing harm.", "Ethical Principles", List.of("nonmaleficence", "ethics")),
            q("ethics-ra-10029", "What is the ethical first step before sharing confidential information with a third party in routine cases?", List.of("Obtain appropriate authorization or consent", "Share everything immediately", "Ask only the third party", "Destroy all records"), 0, QuestionDifficulty.EASY, "Routine disclosure generally requires valid consent or authorization unless a legal or ethical exception applies.", "Confidentiality", List.of("disclosure", "consent")),
            q("ethics-ra-10029", "Which action is most appropriate when test data may be misunderstood by an unqualified recipient?", List.of("Release it without explanation", "Provide interpretation safeguards or limit disclosure as allowed", "Alter the score to avoid confusion", "Ignore test security"), 1, QuestionDifficulty.HARD, "Psychologists should protect test data and provide appropriate interpretation safeguards.", "Testing Ethics", List.of("test-data", "interpretation")),
            q("ethics-ra-10029", "Which ethical value is reflected by treating clients fairly and avoiding discrimination?", List.of("Justice", "Habituation", "Transference", "Shaping"), 0, QuestionDifficulty.EASY, "Justice involves fairness, equal respect, and avoiding discriminatory practice.", "Ethical Principles", List.of("justice", "fairness")),
            q("ethics-ra-10029", "Which action should be taken when a client's legal rights and professional ethics both affect a decision?", List.of("Ignore the law", "Consider both legal requirements and ethical obligations before acting", "Follow convenience only", "Ask an unrelated person to decide"), 1, QuestionDifficulty.MEDIUM, "Complex decisions should consider both applicable law and ethical responsibilities.", "Ethical Decision-Making", List.of("law", "ethics"))
        );
    }

    private SeedQuestion q(
        String topicSlug,
        String text,
        List<String> choices,
        int correctAnswerIndex,
        QuestionDifficulty difficulty,
        String explanation,
        String category,
        List<String> tags
    ) {
        return new SeedQuestion(topicSlug, text, choices, correctAnswerIndex, difficulty, explanation, category, tags);
    }

    private record SeedQuestion(
        String topicSlug,
        String text,
        List<String> choices,
        int correctAnswerIndex,
        QuestionDifficulty difficulty,
        String explanation,
        String category,
        List<String> tags
    ) {
    }
}
